/**
 * Generate the Material Design 3 theme from one seed (BB-102 §102.1).
 *
 * The theme is generated, never hand-authored: regenerating from the seed is the
 * only supported way to change theme color, so a reseed is a one-line change
 * instead of a find-and-replace. Output is committed so reviewers see theme
 * diffs.
 *
 * Run via `npm run gen:theme` (wired into `prebuild`, so the file cannot go
 * stale). The script is bundled by esbuild first: @material/material-color-utilities
 * ships extensionless internal imports, which plain Node ESM cannot resolve.
 *
 * What this must NOT touch: the chart surfaces, the series palette, and the
 * status colors. Those are validated against fixed surfaces and live in
 * chart-tokens.css — a reseed must leave them alone. See DESIGN-BOOK.md §2.2–2.4.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  Hct,
  MaterialDynamicColors,
  SchemeTonalSpot,
  argbFromHex,
  hexFromArgb,
} from "@material/material-color-utilities";

/** The project's namesake. Change this and re-run; change nothing else. */
const SEED = "#7A5230";

/**
 * The role set from DESIGN-BOOK.md §2.1, in the book's order. Curated rather
 * than "every role the library exposes": an unused token is a token someone
 * will reach for without checking whether it means anything here.
 */
const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest",
  "outline", "outlineVariant", "inverseSurface", "inverseOnSurface", "scrim",
];

const kebab = (role) => role.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function scheme(isDark) {
  return new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, 0);
}

function block(isDark, indent = "  ") {
  const s = scheme(isDark);
  return ROLES.map((role) => {
    const color = MaterialDynamicColors[role];
    if (!color) throw new Error(`Unknown M3 role: ${role}`);
    return `${indent}--bb-${kebab(role)}: ${hexFromArgb(color.getArgb(s))};`;
  }).join("\n");
}

// Dark values are declared under BOTH scopes on purpose: the media query covers
// the OS setting, the [data-theme] scope covers the in-app toggle, and the
// toggle must win in both directions. The :not() guard lets an explicit light
// choice beat OS-dark; :where() keeps the media block's specificity at zero so
// the explicit dark scope below still wins.
const css = `/* GENERATED by scripts/gen-theme.mjs — do not edit by hand.
 *
 * Material Design 3 tonal palettes from seed ${SEED}.
 * Regenerate with: npm run gen:theme
 *
 * This file is theme color ONLY. Chart surfaces, the series palette and the
 * status colors are fixed and live in chart-tokens.css — see DESIGN-BOOK.md §2.2.
 */

:root {
${block(false)}
}

@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) {
${block(true, "    ")}
  }
}

:root[data-theme="dark"] {
${block(true)}
}
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/styles/theme.generated.css");
writeFileSync(out, css, "utf8");
console.log(`gen-theme: wrote ${ROLES.length} roles x 2 modes from seed ${SEED}`);
